### ISSUE TITLE
AttributeError: 'function' object has no attribute 'urlparse'

### ISSUE THREAD

**Issue by WeiWang88** [LiuChangFreeman/weibo-chaohua-daily#1]
Traceback (most recent call last):
  File "C:\Test\weibo-chaohua-daily-master\main.py", line 300, in <module>
    main()
  File "C:\Test\weibo-chaohua-daily-master\main.py", line 225, in main
    chaohua_list = chaohua_list + resolve(card_group)
  File "C:\Test\weibo-chaohua-daily-master\main.py", line 87, in resolve
    query = urlparse.urlparse(scheme).query
AttributeError: 'function' object has no attribute 'urlparse'

C:\Test\weibo-chaohua-daily-master>pause
Press any key to continue . . .

**Comment by LiuChangFreeman** [comment]
I have fixed the bug under python3 in this commit
[](https://github.com/LiuChangFreeman/weibo-chaohua-daily/commit/235b66f26ef97898a2cf35e8a9558d553dd09fef)
